package AppeanaFx.p

import tornadofx.PropertyHolder

class PropertyHolder {
    lateinit var propertyHolder: PropertyHolder
    init {
        propertyHolder.run {
            this.accentColor
            this.alignment
            this.alternativeColumnFillVisible
            this.alternativeRowFillVisible
            this.animated
            this.arcHeight
            this.arcWidth
            this.arrowsVisible
            this.backgroundColor
            this.backgroundImage
            this.backgroundInsets
            this.backgroundPosition
            this.backgroundRadius
            this.backgroundRepeat
            this.blendMode
            this.backgroundSize
            this.barFill
            this.barGap
            this.baseColor
            this.blockIncrement
            this.borderColor
            this.borderImageInsets
            this.borderImageRepeat
            this.borderImageSlice
            this.borderImageSource
            this.borderImageWidth
            this.borderInsets
            this.borderRadius
            this.borderStyle
            this.borderWidth
            this.categoryGap
            this.cellHeight
            this.cellSize
            this.cellWidth
            this.clockwise
            this.closeTabAnimation
            this.collapsible
            this.colorLabelVisible
            this.columnHAlignment
            this.contentDisplay
            this.contextMenuEnabled
            this.createSymbols
            this.cursor
            this.displayCaret
            this.effect
            this.ellipsisString
            this.endMargin
            this.faintFocusColor
            this.fill
            this.fillWidth
            this.fillHeight
            this.fitToHeight
            this.fitToWidth
            this.fixedCellSize
            this.focusColor
            this.focusTraversable
            this.font
            this.fontWeight
            this.fontStyle
            this.fontSmoothingType
            this.fontSize
            this.fontScale
            this.fontFamily
            this.gapStartAndEnd
            this.graphic
            this.graphicTextGap
            this.gridLinesVisible
            this.hAlignment
            this.hBarPolicy
            this.hgap
            this.highlightFill
            this.highlightTextFill
            this.horizontalCellSpacing
            this.horizontalGridLinesVisible
            this.horizontalZeroLineVisible
            this.image
            this.indent
            this.indeterminateBarAnimationTime
            this.indeterminateBarEscape
            this.indeterminateBarFlip
            this.indeterminateBarLength
            this.indeterminateSegmentCount
            this.labelLineLength
            this.labelPadding
            this.legendSide
            this.legendVisible
            this.majorTickUnit
            this.maxCellsInRow
            this.maxHeight
            this.maxPageIndicatorCount
            this.maxWidth
            this.mergedProperties
            this.minHeight
            this.minWidth
            this.minorTickCount
            this.minorTickLength
            this.minorTickVisible
            this.opacity
            this.openTabAnimation
            this.orientation
            this.padding
            this.pageInformationAlignment
            this.pageInformationVisible
            this.pannable
            this.pieLabelVisible
            this.positionShape
            this.prefColumnCount
            this.prefColumns
            this.prefHeight
            this.prefRowCount
            this.prefRows
            this.prefTileHeight
            this.prefTileWidth
            this.prefWidth
            this.progressColor
            this.promptTextFill
            this.properties
            this.rotate
            this.rowVAlignment
            this.scaleShape
            this.scaleX
            this.scaleY
            this.scaleZ
            this.scaleShape
            this.selectionBarText
            this.shape
            this.showTickLabels
            this.showTickMarks
            this.showWeekNumbers
            this.side
            this.size
            this.skin
            this.smooth
            this.snapToPixel
            this.snapToTicks
            this.spinEnabled
            this.spacing
            this.startAngle
            this.startMargin
            this.strikethrough
            this.stroke
            this.strokeWidth
            this.strokeType
            this.strokeMiterLimit
            this.strokeLineCap
            this.strokeLineJoin
            this.strokeDashArray
            this.strokeDashOffset
            this.tabMaxHeight
            this.tabMaxWidth
            this.tabMinHeight
            this.tabMinWidth
            this.textAlignment
            this.textBoxBorder
            this.textFill
            this.textOrigin
            this.textOverrun
            this.tickLabelFill
            this.tickLabelFont
            this.tickLabelGap
            this.tickLabelsVisible
            this.tickUnit
            this.tickLength
            this.tickMarkVisible
            this.tileAlignment
            this.titleSide
            this.tooltipVisible
            this.translateX
            this.translateY
            this.translateZ
            this.underline
            this.unitIncrement
            this.unsafeProperties
            this.useSystemMenuBar
            this.vAlignment
            this.vBarPolicy
            this.verticalCellSpacing
            this.verticalGridLinesVisible
            this.verticalZeroLineVisible
            this.vgap
            this.visibility
            this.wrapText
            this.raw("")
            this.unsafe("",1)
//            this.setProperty() // todo
        }
    }
}